name: Auto-merge PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >-
      ${{
        !github.event.pull_request.draft &&
        (
          github.event.pull_request.user.login == 'dependabot[bot]' ||
          (
            github.event.pull_request.user.login == 'github-actions' &&
            startsWith(github.event.pull_request.title, 'Changelog update')
          )
        )
      }}
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.VERSION_PUSH_PAT }}

    steps:
      - id: metadata
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ secrets.VERSION_PUSH_PAT }}

      - run: gh pr review --approve "$PR_URL"

      - if: >-
          ${{
            github.event.pull_request.user.login == 'github-actions' ||
            contains(
              fromJSON('["version-update:semver-patch","version-update:semver-minor","version-update:semver-major"]'),
              steps.metadata.outputs.update-type
            )
          }}
        run: gh pr merge --auto --rebase "$PR_URL"
